"""empty message

Revision ID: 266653a75470
Revises: 2ea1e1135825
Create Date: 2025-05-22 14:33:24.014354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '266653a75470'
down_revision = '2ea1e1135825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', postgresql.BYTEA(), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_server', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('smtp_user', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('smtp_password', sa.String(), nullable=True))
        batch_op.drop_column('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('smtp_password')
        batch_op.drop_column('smtp_user')
        batch_op.drop_column('smtp_server')

    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
