"""empty message

Revision ID: 3278ab7cf918
Revises: 51b13f3e37b4
Create Date: 2025-05-23 18:20:24.258113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3278ab7cf918'
down_revision = '51b13f3e37b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies_settings', ['settings_id'], ['id'])

    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.drop_constraint('companies_settings_company_id_fkey', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('companies_settings_company_id_fkey', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('settings_id')

    # ### end Alembic commands ###
