"""empty message

Revision ID: 41dc6438974a
Revises: 913d9dfcb076
Create Date: 2025-05-24 00:16:56.183465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dc6438974a'
down_revision = '913d9dfcb076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('groups_permissions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'permissions', ['permissions_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('groups_permissions_user_id_fkey', 'permissions', ['user_id'], ['id'])
        batch_op.drop_column('permissions_id')

    # ### end Alembic commands ###
