"""empty message

Revision ID: 4d3806471ee6
Revises: 41dc6438974a
Create Date: 2025-05-24 14:00:50.396564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3806471ee6'
down_revision = '41dc6438974a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id', 'permissions_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
