"""empty message

Revision ID: 51b13f3e37b4
Revises: 579a28c8ed6b
Create Date: 2025-05-23 13:23:21.778410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b13f3e37b4'
down_revision = '579a28c8ed6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('companies_emails_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_unique_constraint('companies_emails_key', ['emails'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
