"""empty message

Revision ID: 52f05a04e31d
Revises: bc77133a816a
Create Date: 2025-05-25 23:08:34.447777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f05a04e31d'
down_revision = 'bc77133a816a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['group_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
