"""empty message

Revision ID: 913d9dfcb076
Revises: deadb410d9e2
Create Date: 2025-05-23 23:39:28.184032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913d9dfcb076'
down_revision = 'deadb410d9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'resource_id', 'action_id', 'application_id')
    )
    op.create_table('groups_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permissions_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permissions_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('permissions_groups')
    op.drop_table('permissions_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='permissions_users_action_id_fkey'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='permissions_users_application_id_fkey'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='permissions_users_company_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='permissions_users_resource_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='permissions_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='permissions_users_pkey'),
    sa.UniqueConstraint('company_id', 'resource_id', 'action_id', 'application_id', 'user_id', name='permissions_users_company_id_resource_id_action_id_applicat_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('permissions_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name='permissions_groups_action_id_fkey'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='permissions_groups_application_id_fkey'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='permissions_groups_company_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='permissions_groups_group_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='permissions_groups_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='permissions_groups_pkey'),
    sa.UniqueConstraint('company_id', 'resource_id', 'action_id', 'application_id', 'group_id', name='permissions_groups_company_id_resource_id_action_id_applica_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users_permissions')
    op.drop_table('groups_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
