"""empty message

Revision ID: a1aff706e2d7
Revises: 3278ab7cf918
Create Date: 2025-05-23 18:50:57.841314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1aff706e2d7'
down_revision = '3278ab7cf918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
