"""empty message

Revision ID: bc77133a816a
Revises: 4d3806471ee6
Create Date: 2025-05-24 14:10:53.183559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc77133a816a'
down_revision = '4d3806471ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['group_id', 'permissions_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
