"""empty message

Revision ID: deadb410d9e2
Revises: a1aff706e2d7
Create Date: 2025-05-23 19:06:51.048460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deadb410d9e2'
down_revision = 'a1aff706e2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('companies_settings_id_fkey', type_='foreignkey')
        batch_op.drop_column('settings_id')

    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('companies_settings_id_fkey', 'companies_settings', ['settings_id'], ['id'])

    # ### end Alembic commands ###
